name: transmission
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - geopandas
  - rasterio
  - folium
  - seaborn
  - jupyter
  - ipykernel
  - requests
  - tqdm
  - openpyxl
  - h5py
  - pip
  - pip:
    - asf_search
